---
- name: Vector | Create Vector group
  become: true
  ansible.builtin.group:
    name: vector
    state: present
- name: Vector | Create Vector user
  become: true
  ansible.builtin.user:
    name: vector
    group: vector
    shell: /bin/noshell

- name: Vector | Create directory for Vector
  become: true
  ansible.builtin.file:
    path: /opt/vector
    state: directory
    mode: "0777"
- name: Vector | Extract archive
  ansible.builtin.unarchive:
    src: https://packages.timber.io/vector/0.30.0/vector-0.30.0-x86_64-unknown-linux-musl.tar.gz
    dest: /opt/vector
    remote_src: true
    extra_opts: [--strip-components=2]

- name: Vector | Create Vector config
  ansible.builtin.template:
    src: vector.yml.j2
    dest: /opt/vector/config/custom_config.yml
    mode: "0644"
  notify: Vector | Run vector as a daemon
- name: Vector | Create Vector service
  become: true
  ansible.builtin.copy:
    src: vector.service
    dest: /etc/systemd/system/vector.service
    mode: "0744"
